import { IStateDetails } from './models';

export const statedetailDbValue: IStateDetails[] =[

    {
        "active": "5559",
        "confirmed": "6817",
        "deaths": "301",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "24/04/2020 20:52:39",
        "recovered": "957",
        "state": "Maharashtra",
        "statecode": "MH",
        "statenotes": ""
    },
    {
        "active": "1604",
        "confirmed": "2514",
        "deaths": "53",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "24/04/2020 21:32:38",
        "recovered": "857",
        "state": "Delhi",
        "statecode": "DL",
        "statenotes": ""
    },
    {
        "active": "2423",
        "confirmed": "2815",
        "deaths": "127",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "24/04/2020 20:21:01",
        "recovered": "265",
        "state": "Gujarat",
        "statecode": "GJ",
        "statenotes": ""
    },
    {
        "active": "1534",
        "confirmed": "2059",
        "deaths": "32",
        "deltaconfirmed": "25",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "25/04/2020 09:52:37",
        "recovered": "493",
        "state": "Rajasthan",
        "statecode": "RJ",
        "statenotes": ""
    },
    {
        "active": "867",
        "confirmed": "1755",
        "deaths": "22",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "24/04/2020 18:17:38",
        "recovered": "866",
        "state": "Tamil Nadu",
        "statecode": "TN",
        "statenotes": ""
    },
    {
        "active": "1544",
        "confirmed": "1846",
        "deaths": "92",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "24/04/2020 17:17:37",
        "recovered": "210",
        "state": "Madhya Pradesh",
        "statecode": "MP",
        "statenotes": ""
    },
    {
        "active": "1370",
        "confirmed": "1621",
        "deaths": "25",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "24/04/2020 19:47:38",
        "recovered": "226",
        "state": "Uttar Pradesh",
        "statecode": "UP",
        "statenotes": ""
    },
    {
        "active": "667",
        "confirmed": "983",
        "deaths": "25",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "25/04/2020 00:32:37",
        "recovered": "291",
        "state": "Telangana",
        "statecode": "TG",
        "statenotes": ""
    },
    {
        "active": "781",
        "confirmed": "955",
        "deaths": "29",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "23/04/2020 14:47:37",
        "recovered": "145",
        "state": "Andhra Pradesh",
        "statecode": "AP",
        "statenotes": ""
    },
    {
        "active": "304",
        "confirmed": "474",
        "deaths": "18",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "24/04/2020 17:57:37",
        "recovered": "152",
        "state": "Karnataka",
        "statecode": "KA",
        "statenotes": ""
    },
    {
        "active": "116",
        "confirmed": "450",
        "deaths": "3",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "24/04/2020 17:12:38",
        "recovered": "331",
        "state": "Kerala",
        "statecode": "KL",
        "statenotes": ""
    },
    {
        "active": "340",
        "confirmed": "454",
        "deaths": "5",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "24/04/2020 19:37:38",
        "recovered": "109",
        "state": "Jammu and Kashmir",
        "statecode": "JK",
        "statenotes": ""
    },
    {
        "active": "450",
        "confirmed": "571",
        "deaths": "18",
        "deltaconfirmed": "57",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "25/04/2020 09:32:37",
        "recovered": "103",
        "state": "West Bengal",
        "statecode": "WB",
        "statenotes": "WB totals and district numbers are currently updated according to https://www.mohfw.gov.in"
    },
    {
        "active": "86",
        "confirmed": "275",
        "deaths": "3",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "24/04/2020 14:52:40",
        "recovered": "186",
        "state": "Haryana",
        "statecode": "HR",
        "statenotes": "One death in Ambala included"
    },
    {
        "active": "211",
        "confirmed": "298",
        "deaths": "17",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "24/04/2020 18:07:38",
        "recovered": "70",
        "state": "Punjab",
        "statecode": "PB",
        "statenotes": ""
    },
    {
        "active": "179",
        "confirmed": "225",
        "deaths": "2",
        "deltaconfirmed": "2",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "25/04/2020 11:07:38",
        "recovered": "44",
        "state": "Bihar",
        "statecode": "BR",
        "statenotes": ""
    },
    {
        "active": "60",
        "confirmed": "94",
        "deaths": "1",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "24/04/2020 16:47:38",
        "recovered": "33",
        "state": "Odisha",
        "statecode": "OR",
        "statenotes": ""
    },
    {
        "active": "23",
        "confirmed": "48",
        "deaths": "0",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "22/04/2020 20:07:38",
        "recovered": "25",
        "state": "Uttarakhand",
        "statecode": "UT",
        "statenotes": ""
    },
    {
        "active": "48",
        "confirmed": "59",
        "deaths": "3",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "24/04/2020 21:52:39",
        "recovered": "8",
        "state": "Jharkhand",
        "statecode": "JH",
        "statenotes": ""
    },
    {
        "active": "20",
        "confirmed": "40",
        "deaths": "2",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "23/04/2020 21:52:49",
        "recovered": "18",
        "state": "Himachal Pradesh",
        "statecode": "HP",
        "statenotes": "Death of Tibetan refugee included"
    },
    {
        "active": "5",
        "confirmed": "37",
        "deaths": "0",
        "deltaconfirmed": "1",
        "deltadeaths": "0",
        "deltarecovered": "2",
        "lastupdatedtime": "25/04/2020 09:37:38",
        "recovered": "32",
        "state": "Chhattisgarh",
        "statecode": "CT",
        "statenotes": ""
    },
    {
        "active": "16",
        "confirmed": "36",
        "deaths": "1",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "20/04/2020 08:45:06",
        "recovered": "19",
        "state": "Assam",
        "statecode": "AS",
        "statenotes": "Includes one case from Nagaland"
    },
    {
        "active": "12",
        "confirmed": "27",
        "deaths": "0",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "24/04/2020 18:52:39",
        "recovered": "15",
        "state": "Chandigarh",
        "statecode": "CH",
        "statenotes": ""
    },
    {
        "active": "2",
        "confirmed": "18",
        "deaths": "0",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "23/04/2020 10:32:40",
        "recovered": "16",
        "state": "Ladakh",
        "statecode": "LA",
        "statenotes": ""
    },
    {
        "active": "18",
        "confirmed": "29",
        "deaths": "0",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "24/04/2020 21:42:40",
        "recovered": "11",
        "state": "Andaman and Nicobar Islands",
        "statecode": "AN",
        "statenotes": ""
    },
    {
        "active": "11",
        "confirmed": "12",
        "deaths": "1",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "18/04/2020 12:38:07",
        "recovered": "0",
        "state": "Meghalaya",
        "statecode": "ML",
        "statenotes": ""
    },
    {
        "active": "0",
        "confirmed": "7",
        "deaths": "0",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "19/04/2020 17:04:07",
        "recovered": "7",
        "state": "Goa",
        "statecode": "GA",
        "statenotes": ""
    },
    {
        "active": "3",
        "confirmed": "7",
        "deaths": "0",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "19/04/2020 08:25:07",
        "recovered": "4",
        "state": "Puducherry",
        "statecode": "PY",
        "statenotes": ""
    },
    {
        "active": "0",
        "confirmed": "2",
        "deaths": "0",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "20/04/2020 10:04:08",
        "recovered": "2",
        "state": "Manipur",
        "statecode": "MN",
        "statenotes": ""
    },
    {
        "active": "0",
        "confirmed": "2",
        "deaths": "0",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "23/04/2020 20:47:41",
        "recovered": "2",
        "state": "Tripura",
        "statecode": "TR",
        "statenotes": ""
    },
    {
        "active": "1",
        "confirmed": "1",
        "deaths": "0",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "26/03/2020 07:19:29",
        "recovered": "0",
        "state": "Mizoram",
        "statecode": "MZ",
        "statenotes": ""
    },
    {
        "active": "0",
        "confirmed": "1",
        "deaths": "0",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "16/04/2020 19:33:11",
        "recovered": "1",
        "state": "Arunachal Pradesh",
        "statecode": "AR",
        "statenotes": ""
    },
    {
        "active": "0",
        "confirmed": "0",
        "deaths": "0",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "20/04/2020 08:45:07",
        "recovered": "0",
        "state": "Nagaland",
        "statecode": "NL",
        "statenotes": ""
    },
    {
        "active": "0",
        "confirmed": "0",
        "deaths": "0",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "17/04/2020 15:03:07",
        "recovered": "0",
        "state": "Dadra and Nagar Haveli",
        "statecode": "DN",
        "statenotes": ""
    },
    {
        "active": "0",
        "confirmed": "0",
        "deaths": "0",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "26/03/2020 07:19:29",
        "recovered": "0",
        "state": "Daman and Diu",
        "statecode": "DD",
        "statenotes": ""
    },
    {
        "active": "0",
        "confirmed": "0",
        "deaths": "0",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "26/03/2020 07:19:29",
        "recovered": "0",
        "state": "Lakshadweep",
        "statecode": "LD",
        "statenotes": ""
    },
    {
        "active": "0",
        "confirmed": "0",
        "deaths": "0",
        "deltaconfirmed": "0",
        "deltadeaths": "0",
        "deltarecovered": "0",
        "lastupdatedtime": "26/03/2020 07:19:29",
        "recovered": "0",
        "state": "Sikkim",
        "statecode": "SK",
        "statenotes": ""
    }
]